### ISSUE TITLE
nativescript support for checkbox, select, datepicker, textarea field types

### ISSUE THREAD

**Issue by dhiles** [formly-js/ngx-formly#1221] opened 2018-10-04 23:02 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

**Current behavior**

ngx-formly nativescript version currently only supports text field 

**Expected behavior**

nativescript supports for checkbox, select, datepicker, textarea field types
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

want to load a variety of field types in a nativescript ngx-formly form

**Please tell us about your environment:**

* **Angular version:** 2.0.X

6.1.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.7.2
* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment] 2018-10-04 23:48
duplicate of #1167, PR welcomed!

**Closed by aitboudad** 2018-10-04 23:48 UTC
