### ISSUE TITLE
ExpressionProperties in Wrapper bug

### ISSUE THREAD

**Issue by davidoween** [formly-js/ngx-formly#844] opened 2018-03-27 11:24 UTC
[x] Small bug

Maximum call stack size exceeded

There two problems

When there is an expressionPropierty in a wrapper and its fields also have a expressionPropierty.

(DEMO)

https://stackblitz.com/edit/angular-lqtphb?file=app/app.component.ts

Disabled no working with @angular/forms@5.2.9. Since 5.2.0 no work. 

(DEMO)

https://stackblitz.com/edit/angular-aphhdv?file=app/app.component.ts

**Comment by aitboudad** [comment] 2018-03-27 16:05
first example fixed in `2.0.0-rc.49`, 
the second one still buggy, I'll look into it later.

**Comment by aitboudad** [comment] 2018-03-30 09:15
after trying several approach with no consistent result due to how disabled state work in angular reactive-form and some unexpected behavior (maybe a bug in angular need some investigations), I decided to revert my last fixed that take account of  disabled state in child fields.

To make you example work you have to avoid using set disabled expression property on fieldGroup field.
https://stackblitz.com/edit/angular-xd7wuu.

**Comment by davidoween** [comment] 2018-03-30 09:28
but we need using set disabled expression property on fieldGroup field. We have many children and dynamically add dynamism expression property. This is very important for us

**Comment by davidoween** [comment] 2018-03-30 09:41
After trying the example at least it does not show errors in the console, even if the expression property in the children does not work. It can be valid.

**Comment by aitboudad** [comment] 2018-03-30 09:53
the issue is if we disable parent then followed by enable child it doesn't produce a consistent result, sometimes all fields are enabled and sometimes it disable all fields.
```ts
parent.disable();
child1.enable();
child2.disable();
```
so in order to avoid that we should use one way to toggle field status.

You use-case is a valid one, maybe we can introduce an option or just using fieldTransformer that move the parent disabled condition into its the children.

any hint on the option name ?

**Comment by davidoween** [comment] 2018-03-30 10:10
Could it be that the children fields have priority over the parent fields?

**Comment by aitboudad** [comment] 2018-03-30 10:17
> Can it be an option that forces the removal of the father's property?

yep, if that option is passed we will apply https://github.com/formly-js/ngx-formly/pull/847, it should be only applied for disabled state right now.

**Comment by aitboudad** [comment] 2018-04-02 10:10
I updated the example to include the patch in #847 see https://stackblitz.com/edit/angular-xd7wuu, using 
```ts
    FormlyModule.forRoot({
      ...
      extras: {
        fieldTransform: [formlyFieldTransform],
      }
    }),
```
 you can use it now until we come with a proper solution.

I'll revised this issue on next major version.

**Comment by smile2014** [comment] 2018-05-18 08:35
FormlyForm.html:2 ERROR TypeError: Cannot read property 'eval' of undefined
    at eval (eval at _loop_1 (apes-form.component.ts:128), <anonymous>:3:112)
    at FormlyField.push../node_modules/@ngx-formly/core/esm5/ngx-formly-core.js.FormlyField.lifeCycleHooks (ngx-formly-core.js:1056)
    at FormlyField.push../node_modules/@ngx-formly/core/esm5/ngx-formly-core.js.FormlyField.ngOnInit (ngx-formly-core.js:1003)
    at checkAndUpdateDirectiveInline (core.js:10097)
    at checkAndUpdateNodeInline (core.js:11363)
    at checkAndUpdateNode (core.js:11325)
    at debugCheckAndUpdateNode (core.js:11962)
    at debugCheckDirectivesFn (core.js:11922)
    at Object.eval [as updateDirectives] (FormlyForm.html:2)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:11914)

**Comment by smile2014** [comment] 2018-05-18 10:05
export class FormlyFieldInput extends ApesField

export class ApesField extends FieldType{

  protected onDestroy$ = new Subject<any>();

  protected oldValues = {};

  constructor(protected apiService: ApiService, protected events: Events, protected expressionService: ExpressionService) {
    super();
  }

  ngOnDestroy(): void {
    this.onDestroy$.next();
    this.onDestroy$.complete();
  }
  interceptFrom(fieldName: string, expression: string) {}


Use this to not get the interceptFrom method

**Closed** 2018-08-05 13:26 UTC
Labels: enhancement
