### ISSUE TITLE
Field that is required and hidden is ng-invalid

### ISSUE THREAD

**Issue by Ore4444** [formly-js/ngx-formly#638] opened 2018-01-09 19:09 UTC
**I'm submitting a ...** 
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
An required element with a hideExpression that resolves to true is hidden from view but is still considered required.

**Expected behavior**
When a required field is hidden it should stop being required.

**Minimal reproduction of the problem with instructions**
```
{
    type           : 'input',
    key            : 'radius',
    templateOptions: {label: 'Radius: ', type: 'number', required: true},
    hideExpression : () => true,
},
```

**What is the motivation / use case for changing the behavior?**

Intuitively, if business logic states a field is hidden and user cannot fill the field, it doesn't make sense to prevent submission of form until the field is filled.

**Please tell us about your environment:**

* **Angular version:** 5.1.3

* **Browser:** all
 
* **Language:** all

Thanks a lot for all the effort put into this! I've been working with this tool daily for the past 2 weeks and it's amazing!!

**Comment by aitboudad** [comment] 2018-01-09 19:40
> Thanks a lot for all the effort put into this! I've been working with this tool daily for the past 2 weeks and it's amazing!!

:smiley: glad to hear that.

anyway, I'm not able to reproduce your issue here is a example: https://stackblitz.com/edit/angular-euheew

**Comment by Ore4444** [comment] 2018-01-10 10:35
Thank you for the quick answer.
I will fork your stackblitz and copy over my code until the bug happens.
Then, I'll report back here soon.

**Comment by Jinpeiqi** [comment] 2018-01-11 10:19
We have reproduce this issue.  https://stackblitz.com/edit/angular-scmm4t
Hide parent will not disable child validation

**Comment by aitboudad** [comment] 2018-01-11 12:24
@Jinpeiqi fixed in `2.0.0-rc.10`

**Comment by Ore4444** [comment] 2018-01-11 16:06
Wow! I'm amazed!
First time I experience the power of open source first-hand.
Now I'm gonna tell all my friends how awesome open source is.

**Comment by geraldapeoples** [comment] 2018-01-11 16:40
:o)

**Comment by geraldapeoples** [comment] 2018-01-11 16:41
Not just open source, the formly project is really awesome!

**Comment by aitboudad** [comment] 2018-01-11 17:32
I'm going to close this issue :(.
Thanks for everyone!

**Closed by aitboudad** 2018-01-11 17:32 UTC
Labels: bug
